name: speech_synthesis
description: Text to speech app.
version: 0.1.0
homepage: https://javascript30.com/

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  path: ^1.6.0
  js: ^0.6.1+1

dev_dependencies:
  build_runner: ^1.6.0
  build_web_compilers: ^2.3.0
  effective_dart: ^1.2.1
